# See: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file
version: 2

updates:
  # Configure check for outdated GitHub Actions actions in workflows.
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/dependabot/README.md
  # See: https://docs.github.com/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: github-actions
    directory: /.github/workflows/
    open-pull-requests-limit: 100
    schedule:
      interval: daily
    labels:
      - "topic: infrastructure"
    assignees:
      - per1234

  # Configure check for outdated GitHub Actions actions in workflow templates.
  - package-ecosystem: github-actions
    directory: /workflow-templates/
    open-pull-requests-limit: 100
    schedule:
      interval: daily
    labels:
      - "topic: infrastructure"
    assignees:
      - per1234

  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: daily
    labels:
      - "topic: infrastructure"
    assignees:
      - per1234

  - package-ecosystem: pip
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: daily
    labels:
      - "topic: infrastructure"
    assignees:
      - per1234
