# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-toc-task.md
name: Check ToC

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-toc-task.ya?ml"
      # TODO: Update this if ToC of any other files should be checked.
      - "README.md"
  pull_request:
    paths:
      - ".github/workflows/check-toc-task.ya?ml"
      # TODO: Update this if ToC of any other files should be checked.
      - "README.md"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    name: ${{ matrix.file.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        file:
          # TODO: Update this if any other files should be checked.
          - name: README.md
            # Max ToC depth, for use with the markdown-toc --maxdepth flag.
            maxdepth: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Rebuild ToC
        run: |
          task markdown:toc \
            FILE_PATH="${{ github.workspace }}/${{ matrix.file.name }}" \
            MAX_DEPTH=${{ matrix.file.maxdepth }}

      - name: Check ToC
        run: git diff --color --exit-code
