# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-general-formatting-task/Taskfile.yml
  general:check-formatting:
    desc: Check basic formatting style of all files
    cmds:
      - |
        if
          ! which go \
          &>/dev/null
        then
          echo "Go not found or not in PATH."
          echo "Please install: https://go.dev/doc/install"
          exit 1
        fi
      - |
        go tool \
          github.com/editorconfig-checker/editorconfig-checker/v3/cmd/editorconfig-checker
