# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
  general:cache-dep-licenses:
    desc: Cache dependency license metadata
    deps:
      - task: general:prepare-deps
    cmds:
      - |
        if
          ! which licensed \
          &>/dev/null
        then
          if [[ {{OS}} == "windows" ]]; then
            echo "Licensed does not have Windows support."
            echo "Please use Linux/macOS or download the dependencies cache from the GitHub Actions workflow artifact."
          else
            echo "licensed not found or not in PATH."
            echo "Please install: https://github.com/licensee/licensed#installation"
          fi
          exit 1
        fi
      - licensed cache

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
  general:check-dep-licenses:
    desc: Check for unapproved dependency licenses
    deps:
      - task: general:cache-dep-licenses
    cmds:
      - |
        MATCHES="$(
          find \
            .licenses \
            -regex '.+\.yml' \
            -type f \
            -print0 \
          | \
            xargs \
              --null \
              go tool \
                github.com/mikefarah/yq/v4 \
                  'select(.license == "other") | filename'
        )"
        if [[ "$MATCHES" != "" ]]; then
          printf "%s" "$MATCHES"
          echo
          echo "The license cache files above have the license set to 'other'. Please manually define the license type and retry."
          echo "See: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-go-dependencies-task.md#unrecognized-licenses"
          exit 1
        fi
      - licensed status
