# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/test-python-poetry-task/Taskfile.yml
  python:test:
    desc: Run Python tests
    deps:
      - task: poetry:install-deps
    cmds:
      - |
        poetry run \
          pytest \
            tests
