# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  docs:generate:
    desc: Create all generated documentation content
    # This is an "umbrella" task used to call any documentation generation processes the project has.
    # It can be left empty if there are none.

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
  markdown:check-links:
    desc: Check for broken links
    deps:
      - task: docs:generate
      - task: npm:install-deps
    cmds:
      - |
        if [[ "{{.OS}}" == "Windows_NT" ]]; then
          # npx --call uses the native shell, which makes it too difficult to use npx for this application on Windows,
          # so the Windows user is required to have markdown-link-check installed and in PATH.
          if ! which markdown-link-check &>/dev/null; then
            echo "markdown-link-check not found or not in PATH."
            echo "Please install: https://github.com/tcort/markdown-link-check#readme"
            exit 1
          fi
          # Using -regex instead of -name to avoid Task's behavior of globbing even when quoted on Windows
          # The odd method for escaping . in the regex is required for windows compatibility because mvdan.cc/sh gives
          # \ characters special treatment on Windows in an attempt to support them as path separators.
          find . \
            -type d -name ".git" -prune -o \
            -type d -name ".licenses" -prune -o \
            -type d -name "__pycache__" -prune -o \
            -type d -name "node_modules" -prune -o \
            -regex ".*[.]md" \
            -exec \
              markdown-link-check \
                --quiet \
                --config "./.markdown-link-check.json" \
                \{\} \
                +
        else
          npx --package=markdown-link-check --call='
            find . \
              -type d -name ".git" -prune -o \
              -type d -name ".licenses" -prune -o \
              -type d -name "__pycache__" -prune -o \
              -type d -name "node_modules" -prune -o \
              -regex ".*[.]md" \
              -exec \
                markdown-link-check \
                  --quiet \
                  --config "./.markdown-link-check.json" \
                  \{\} \
                  +
          '
        fi

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
  markdown:fix:
    desc: Automatically correct linting violations in Markdown files where possible
    deps:
      - task: npm:install-deps
    cmds:
      - npx markdownlint-cli --fix "**/*.md"

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
  markdown:lint:
    desc: Check for problems in Markdown files
    deps:
      - task: npm:install-deps
    cmds:
      - npx markdownlint-cli "**/*.md"
