# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-files-task/Taskfile.yml
  general:check-filenames:
    desc: Check for non-portable filenames
    cmds:
      - |
        find . \
          -type d -name '.git' -prune -o \
          -type d -name '.licenses' -prune -o \
          -type d -name '__pycache__' -prune -o \
          -type d -name 'node_modules' -prune -o \
          -exec \
            sh \
              -c ' \
                basename "$0" \
                | \
                grep \
                  --extended-regexp \
                  --regexp='"'"'([<>:"/\\|?*'"'"'"$(printf "\001-\037")"'"'"'])|(.+\.$)'"'"' \
                  --silent \
                && \
                echo "$0"
              ' \
              '{}' \
            \; \
          -execdir \
            false \
            '{}' \
            + \
        || \
        {
          echo
          echo "Prohibited characters found in filenames"
          echo "See:"
          echo "https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions:~:text=except%20for%20the%20following"
          false
        }
      - |
        find . \
          -type d -name '.git' -prune -o \
          -type d -name '.licenses' -prune -o \
          -type d -name '__pycache__' -prune -o \
          -type d -name 'node_modules' -prune -o \
          -exec \
            sh \
              -c ' \
                basename "$0" \
                | \
                grep \
                  --ignore-case \
                  --extended-regexp \
                  --regexp='"'"'^(con|prn|aux|nul|com[0-9]+|lpt[0-9]+)$'"'"' \
                  --silent \
                && \
                echo "$0"
              ' \
              '{}' \
            \; \
          -execdir \
            false \
            '{}' \
            + \
        || \
        {
          echo
          echo "Reserved filenames found"
          echo "See:"
          echo "https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions:~:text=use%20the%20following-,reserved%20names,-for%20the%20name"
          false
        }

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-files-task/Taskfile.yml
  general:check-symlinks:
    desc: Check for bad symlinks
    cmds:
      - |
        find . \
          -type d -name '.git' -prune -o \
          -type d -name '.licenses' -prune -o \
          -type d -name '__pycache__' -prune -o \
          -type d -name 'node_modules' -prune -o \
          -type l \
          -execdir \
            test ! -e '{}' \
            \; \
          -exec \
            echo '{}' \
            \; \
          -execdir \
            false \
            '{}' \
            + \
        || \
        {
          echo 'Broken or circular symlink found'
          false
        }
