# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/npm-task/Taskfile.yml
  npm:install-deps:
    desc: |
      Install dependencies managed by npm.
      Environment variable parameters:
      - PROJECT_PATH: Path of the npm-managed project (default: "./").
    run: when_changed
    dir: |
      "{{default "./" .PROJECT_PATH}}"
    cmds:
      - npm install
