# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  # Parameter variables:
  # - PROJECT_PATH: path of the npm-managed project. Default value: "./"
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/npm-task/Taskfile.yml
  npm:install-deps:
    desc: Install dependencies managed by npm
    run: when_changed
    dir: |
      "{{default "./" .PROJECT_PATH}}"
    cmds:
      - npm install
