# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  # Parameter variables:
  # - SCRIPT_PATH: path of the script to be checked.
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-shell-task/Taskfile.yml
  shell:check:
    desc: Check for problems with shell scripts
    cmds:
      - |
        if [[ "{{.SCRIPT_PATH}}" == "" ]]; then
          echo "Path to script file must be passed to this task via the SCRIPT_PATH taskfile variable."
          echo "See: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-shell-task.md#usage"
          exit 1
        fi
      - |
        if ! which shellcheck &>/dev/null; then
          echo "shellcheck not installed or not in PATH."
          echo "Please install: https://github.com/koalaman/shellcheck#installing"
          exit 1
        fi
      - |
        shellcheck \
          --format={{default "tty" .SHELLCHECK_FORMAT}} \
          "{{.SCRIPT_PATH}}"

  # Parameter variables:
  # - SCRIPT_PATH: path of the script to be checked.
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-shell-task/Taskfile.yml
  shell:check-mode:
    desc: Check for non-executable shell scripts
    cmds:
      - |
        if [[ "{{.SCRIPT_PATH}}" == "" ]]; then
          echo "Path to script file must be passed to this task via the SCRIPT_PATH taskfile variable."
          echo "See: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-shell-task.md#usage"
          exit 1
        fi
      - |
        test -x "{{.SCRIPT_PATH}}"

  # Parameter variables:
  # - SCRIPT_PATH: path of the script to be formatted.
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-shell-task/Taskfile.yml
  shell:format:
    desc: Format shell script files
    cmds:
      - |
        if [[ "{{.SCRIPT_PATH}}" == "" ]]; then
          echo "Path to script file must be passed to this task via the SCRIPT_PATH taskfile variable."
          echo "See: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-shell-task.md#usage"
          exit 1
        fi
      - |
        if ! which shfmt &>/dev/null; then
          echo "shfmt not installed or not in PATH. Please install: https://github.com/mvdan/sh#shfmt"
          exit 1
        fi
      - shfmt -w "{{.SCRIPT_PATH}}"
