# See: https://taskfile.dev/#/usage
version: "3"

vars:
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/go-task/Taskfile.yml
  # Path of the project's primary Go module:
  DEFAULT_GO_MODULE_PATH: .
  DEFAULT_GO_PACKAGES:
    sh: |
      echo $(
        cd {{default .DEFAULT_GO_MODULE_PATH .GO_MODULE_PATH}} &&
        go list ./... | tr '\n' ' ' ||
        echo '"ERROR: Unable to discover Go packages"'
      )
  # `-ldflags` flag to use for `go build` command
  # TODO: define flag if required by the project, or leave empty if not needed.
  LDFLAGS:

tasks:
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/go-task/Taskfile.yml
  go:build:
    desc: Build the Go code
    dir: "{{.DEFAULT_GO_MODULE_PATH}}"
    cmds:
      - |
        go build \
          -v \
          {{.LDFLAGS}}
