# See: https://taskfile.dev/#/usage
version: "3"

vars:
  # `-ldflags` flag to use for `go test` command
  # TODO: define flag if required by the project, or leave empty if not needed.
  TEST_LDFLAGS:

tasks:
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/test-go-task/Taskfile.yml
  go:test:
    desc: |
      Run unit tests.
      Environment variable parameters:
      - GO_MODULE_PATH: Path of the Go module root (default: {{.DEFAULT_GO_MODULE_PATH}}).
      - GO_PACKAGES: List of Go packages to test (default: all packages of the module).
    dir: "{{default .DEFAULT_GO_MODULE_PATH .GO_MODULE_PATH}}"
    cmds:
      - |
        go test \
          -v \
          -short \
          -run '{{default ".*" .GO_TEST_REGEX}}' \
          {{default "-timeout 10m -coverpkg=./... -covermode=atomic" .GO_TEST_FLAGS}} \
          -coverprofile=coverage_unit.txt \
          {{.TEST_LDFLAGS}} \
          {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
