name: Check Label Configuration

# See: https://docs.github.com/actions/reference/workflows-and-actions/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-labels.yml"
      - "workflow-templates/assets/sync-labels/arduino-tooling-gh-label-configuration-schema.json"
      - "workflow-templates/assets/sync-labels/*.ya?ml"
      - "go.mod"
      - "go.sum"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
  pull_request:
    paths:
      - ".github/workflows/check-labels.yml"
      - "workflow-templates/assets/sync-labels/arduino-tooling-gh-label-configuration-schema.json"
      - "workflow-templates/assets/sync-labels/*.ya?ml"
      - "go.mod"
      - "go.sum"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
  schedule:
    # Run periodically to catch breakage caused by external changes.
    - cron: "0 18 * * WED"
  workflow_dispatch:
  repository_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Validate repository label configuration files
        run: |
          go tool \
            github.com/go-task/task/v3/cmd/task labels:validate
