# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-javascript-task.md
name: Check JavaScript

# See: https://docs.github.com/actions/reference/workflows-and-actions/events-that-trigger-workflows
on:
  create:
  push:
    paths:
      - ".github/workflows/check-javascript-task.ya?ml"
      - ".eslintignore"
      - "**/.eslintrc*"
      - ".npmrc"
      - "go.mod"
      - "go.sum"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "**.jsx?"
  pull_request:
    paths:
      - ".github/workflows/check-javascript-task.ya?ml"
      - ".eslintignore"
      - "**/.eslintrc*"
      - ".npmrc"
      - "go.mod"
      - "go.sum"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "**.jsx?"
  workflow_dispatch:
  repository_dispatch:

jobs:
  run-determination:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      result: ${{ steps.determination.outputs.result }}
    steps:
      - name: Determine if the rest of the workflow should run
        id: determination
        run: |
          RELEASE_BRANCH_REGEX="refs/heads/[0-9]+.[0-9]+.x"
          # The `create` event trigger doesn't support `branches` filters, so it's necessary to use Bash instead.
          if [[
            "${{ github.event_name }}" != "create" ||
            "${{ github.ref }}" =~ $RELEASE_BRANCH_REGEX
          ]]; then
            # Run the other jobs.
            RESULT="true"
          else
            # There is no need to run the other jobs.
            RESULT="false"
          fi

          echo "result=$RESULT" >>$GITHUB_OUTPUT

  check:
    needs: run-determination
    if: needs.run-determination.outputs.result == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Lint
        run: |
          go tool \
            github.com/go-task/task/v3/cmd/task js:lint
