name: Check Label Configuration

# See: https://docs.github.com/actions/reference/workflows-and-actions/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-labels.yml"
      - "workflow-templates/assets/sync-labels/arduino-tooling-gh-label-configuration-schema.json"
      - "workflow-templates/assets/sync-labels/*.ya?ml"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
  pull_request:
    paths:
      - ".github/workflows/check-labels.yml"
      - "workflow-templates/assets/sync-labels/arduino-tooling-gh-label-configuration-schema.json"
      - "workflow-templates/assets/sync-labels/*.ya?ml"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
  schedule:
    # Run periodically to catch breakage caused by external changes.
    - cron: "0 18 * * WED"
  workflow_dispatch:
  repository_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Validate repository label configuration files
        run: task labels:validate
