name: Check ESLint Configuration

# See: https://docs.github.com/actions/reference/workflows-and-actions/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-eslint.yml"
      - "workflow-templates/assets/check-javascript/.eslintrc.yml"
      - ".npmrc"
      - "go.mod"
      - "go.sum"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
  pull_request:
    paths:
      - ".github/workflows/check-eslint.yml"
      - "workflow-templates/assets/check-javascript/.eslintrc.yml"
      - ".npmrc"
      - "go.mod"
      - "go.sum"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage resulting from changes to the JSON schema.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json

      - name: Validate workflows
        run: |
          go tool \
            github.com/go-task/task/v3/cmd/task \
              --silent \
              eslint:validate
